export enum COMPONENT_TYPE_ENUM {
  TITLE = 'TITLE',
  TEXT = 'TEXT',
  BUTTON = 'BUTTON',
  PRINCIPLES_CARD = 'PRINCIPLES_CARD',
  INFORMATION_CARD = 'INFORMATION_CARD',
  SERVICE_CARD = 'SERVICE_CARD',
  BANNER = 'BANNER',
}
