export const states = [
  { uf: 'AC', name: 'Acre', value: 1 },
  { uf: 'AL', name: 'Alagoas', value: 2 },
  { uf: 'AP', name: 'Amapá', value: 3 },
  { uf: 'AM', name: 'Amazonas', value: 4 },
  { uf: 'BA', name: 'Bahia', value: 5 },
  { uf: 'CE', name: 'Ceará', value: 6 },
  { uf: 'DF', name: 'Distrito Federal', value: 7 },
  { uf: 'ES', name: 'Espírito Santo', value: 8 },
  { uf: 'GO', name: 'Goiás', value: 9 },
  { uf: 'MA', name: 'Maranhão', value: 10 },
  { uf: 'MT', name: 'Mato Grosso', value: 11 },
  { uf: 'MS', name: 'Mato Grosso do Sul', value: 12 },
  { uf: 'MG', name: 'Minas Gerais', value: 13 },
  { uf: 'PA', name: 'Pará', value: 14 },
  { uf: 'PB', name: 'Paraíba', value: 15 },
  { uf: 'PR', name: 'Paraná', value: 16 },
  { uf: 'PE', name: 'Pernambuco', value: 17 },
  { uf: 'PI', name: 'Piauí', value: 18 },
  { uf: 'RJ', name: 'Rio de Janeiro', value: 19 },
  { uf: 'RN', name: 'Rio Grande do Norte', value: 20 },
  { uf: 'RS', name: 'Rio Grande do Sul', value: 21 },
  { uf: 'RO', name: 'Rondônia', value: 22 },
  { uf: 'RR', name: 'Roraima', value: 23 },
  { uf: 'SC', name: 'Santa Catarina', value: 24 },
  { uf: 'SP', name: 'São Paulo', value: 25 },
  { uf: 'SE', name: 'Sergipe', value: 26 },
  { uf: 'TO', name: 'Tocantins', value: 27 },
];
